### PR TITLE
This is jsut to make me a person

### PR DESCRIPTION
**Pull request by InvitedRhino683**

### CODE REVIEW

**Comment by ZtereoHYPE** [comment]
why though

**Comment by InvitedRhino683** [comment]
make me contributor or else lol

**Comment by ZtereoHYPE** [comment]
tell me three good reasons to accept this pull request

**Review by ZtereoHYPE — COMMENTED** [review]
okay so everything is nice, except for everything. remove all changed and keep the bee movie and I'm accepting it.

**Comment by ZtereoHYPE** [comment]
its too messed up. open a new one with the bee movie only lol

**Pull request closed without merging**
